/* ETA'*/
DROP TEMPORARY TABLE IF EXISTS ETA;

CREATE TEMPORARY TABLE ETA AS
SELECT
CLIENTE.ID_CLIENTE,
TIMESTAMPDIFF(YEAR, DATA_NASCITA, CURDATE()) AS ETA
FROM BANCA.CLIENTE;

SELECT * FROM ETA;

/*N° DI TRANSAZIONI IN USCITA IN TUTTI I CONTI*/
DROP TEMPORARY TABLE IF EXISTS N_TRANS_USCITA;

CREATE TEMPORARY TABLE N_TRANS_USCITA AS
SELECT
CLIENTE.ID_CLIENTE,
COUNT(CASE WHEN SEGNO = '-' THEN 1 ELSE NULL END) AS N_TRANS_USCITA
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM N_TRANS_USCITA;

/*N° DI TRANSAZIONI IN ENTRATA IN TUTTI I CONTI*/
DROP TEMPORARY TABLE IF EXISTS N_TRANS_ENTRATA;

CREATE TEMPORARY TABLE N_TRANS_ENTRATA AS
SELECT
CLIENTE.ID_CLIENTE,
COUNT(CASE WHEN SEGNO = '+' THEN 1 ELSE NULL END) AS N_TRANS_ENTRATA
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM N_TRANS_ENTRATA;

/* IMPORTO TRANSAZIONI IN USCITA IN TUTTI I CONTI */
DROP TEMPORARY TABLE IF EXISTS IMP_TRANS_USCITA;

CREATE TEMPORARY TABLE IMP_TRANS_USCITA AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN SEGNO = '-' THEN IMPORTO ELSE NULL END) AS IMP_TRANS_USCITA
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM IMP_TRANS_USCITA;

/* IMPORTO TRANSAZIONI IN ENTRATA IN TUTTI I CONTI */
DROP TEMPORARY TABLE IF EXISTS IMP_TRANS_ENTRATA;

CREATE TEMPORARY TABLE IMP_TRANS_ENTRATA AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN SEGNO = '+' THEN IMPORTO ELSE NULL END) AS IMP_TRANS_ENTRATA
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM IMP_TRANS_ENTRATA;

/* N° TOTALE DI CONTI CLIENTE  */
DROP TEMPORARY TABLE IF EXISTS COUNT_CONTO_ID;

CREATE TEMPORARY TABLE COUNT_CONTO_ID AS
SELECT 
CLIENTE.ID_CLIENTE,
COUNT(ID_CONTO) AS COUNT_CONTO_ID
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
GROUP BY 1;

SELECT * FROM COUNT_CONTO_ID;

/* N° DI CONTI PER TIPOLOGIA -DISTINTA- */
DROP TEMPORARY TABLE IF EXISTS CONTO_TIPOLOGIA;

CREATE TEMPORARY TABLE CONTO_TIPOLOGIA AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN ID_TIPO_CONTO = 0 THEN 1 ELSE 0 END) AS CONTO_TIPOLOGIA_BASE,
SUM(CASE WHEN ID_TIPO_CONTO = 1 THEN 1 ELSE 0 END) AS CONTO_TIPOLOGIA_BUSINESS,
SUM(CASE WHEN ID_TIPO_CONTO = 2 THEN 1 ELSE 0 END) AS CONTO_TIPOLOGIA_PRIVATI,
SUM(CASE WHEN ID_TIPO_CONTO = 3 THEN 1 ELSE 0 END) AS CONTO_TIPOLOGIA_FAMIGLIE
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
GROUP BY 1;

SELECT * FROM CONTO_TIPOLOGIA;

/* N° TRANSAZIONI IN USCITA PER TIPOLOGIA -DISTINTE- */
DROP TEMPORARY TABLE IF EXISTS TRANS_USCITA_TIPO;

CREATE TEMPORARY TABLE TRANS_USCITA_TIPO AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN ID_TIPO_TRANS = 3 THEN 1 ELSE 0 END) AS TIPO_TRANS_AMAZON,
SUM(CASE WHEN ID_TIPO_TRANS = 4 THEN 1 ELSE 0 END) AS TIPO_TRANS_MUTUO,
SUM(CASE WHEN ID_TIPO_TRANS = 5 THEN 1 ELSE 0 END) AS TIPO_TRANS_HOTEL,
SUM(CASE WHEN ID_TIPO_TRANS = 6 THEN 1 ELSE 0 END) AS TIPO_TRANS_VOLO,
SUM(CASE WHEN ID_TIPO_TRANS = 7 THEN 1 ELSE 0 END) AS TIPO_TRANS_SUPERMERCATO
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
GROUP BY 1;

SELECT * FROM TRANS_USCITA_TIPO;

/* N° TRANSAZIONI IN ENTRATA PER TIPOLOGIA -DISTINTE- */
DROP TEMPORARY TABLE IF EXISTS TRANS_ENTRATA_TIPO;

CREATE TEMPORARY TABLE TRANS_ENTRATA_TIPO AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN ID_TIPO_TRANS = 0 THEN 1 ELSE 0 END) AS TIPO_TRANS_STIPENDIO,
SUM(CASE WHEN ID_TIPO_TRANS = 1 THEN 1 ELSE 0 END) AS TIPO_TRANS_PENSIONE,
SUM(CASE WHEN ID_TIPO_TRANS = 2 THEN 1 ELSE 0 END) AS TIPO_TRANS_DIVIDENDI
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
GROUP BY 1;

SELECT * FROM TRANS_ENTRATA_TIPO;

/* IMPORTO TRANSAZIONE IN USCITA PER TIPOLOGIA CONTO -DISTINTE- */
DROP TEMPORARY TABLE IF EXISTS IMPORTO_TIPO_USCITA;

CREATE TEMPORARY TABLE IMPORTO_TIPO_USCITA AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN SEGNO = '-' AND ID_TIPO_CONTO = 0 THEN IMPORTO ELSE 0 END) AS IMP_OUT_CONTO_BASE,
SUM(CASE WHEN SEGNO = '-' AND ID_TIPO_CONTO = 1 THEN IMPORTO ELSE 0 END) AS IMP_OUT_CONTO_BUSINESS,
SUM(CASE WHEN SEGNO = '-' AND ID_TIPO_CONTO = 2 THEN IMPORTO ELSE 0 END) AS IMP_OUT_CONTO_PRIVATI,
SUM(CASE WHEN SEGNO = '-' AND ID_TIPO_CONTO = 3 THEN IMPORTO ELSE 0 END) AS IMP_OUT_CONTO_FAMIGLIE
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM IMPORTO_TIPO_USCITA;

/* IMPORTO TRANSAZIONE IN ENTRATA PER TIPOLOGIA DI CONTO -DISTINTE- */
DROP TEMPORARY TABLE IF EXISTS IMPORTO_TIPO_ENTRATA;

CREATE TEMPORARY TABLE IMPORTO_TIPO_ENTRATA AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN SEGNO = '+' AND ID_TIPO_CONTO = 0 THEN IMPORTO ELSE 0 END) AS IMP_IN_CONTO_BASE,
SUM(CASE WHEN SEGNO = '+' AND ID_TIPO_CONTO = 1 THEN IMPORTO ELSE 0 END) AS IMP_IN_CONTO_BUSINESS,
SUM(CASE WHEN SEGNO = '+' AND ID_TIPO_CONTO = 2 THEN IMPORTO ELSE 0 END) AS IMP_IN_CONTO_PRIVATI,
SUM(CASE WHEN SEGNO = '+' AND ID_TIPO_CONTO = 3 THEN IMPORTO ELSE 0 END) AS IMP_IN_CONTO_FAMIGLIE
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM IMPORTO_TIPO_ENTRATA;

/*RIEPILOGO FINALE*/
DROP TABLE IF EXISTS TABELLA_SINTESI;

CREATE TABLE TABELLA_SINTESI AS
SELECT
ETA.*,
N_TRANS_USCITA.N_TRANS_USCITA,
N_TRANS_ENTRATA.N_TRANS_ENTRATA,
IMP_TRANS_USCITA.IMP_TRANS_USCITA,
IMP_TRANS_ENTRATA.IMP_TRANS_ENTRATA,
COUNT_CONTO_ID.COUNT_CONTO_ID,
CONTO_TIPOLOGIA.CONTO_TIPOLOGIA_BASE,CONTO_TIPOLOGIA_BUSINESS,CONTO_TIPOLOGIA_PRIVATI,CONTO_TIPOLOGIA_FAMIGLIE,
TRANS_USCITA_TIPO.TIPO_TRANS_AMAZON,TIPO_TRANS_MUTUO,TIPO_TRANS_VOLO,TIPO_TRANS_HOTEL,TIPO_TRANS_SUPERMERCATO,
TRANS_ENTRATA_TIPO.TIPO_TRANS_STIPENDIO,TIPO_TRANS_PENSIONE,TIPO_TRANS_DIVIDENDI,
IMPORTO_TIPO_USCITA.IMP_OUT_CONTO_BASE,IMP_OUT_CONTO_BUSINESS,IMP_OUT_CONTO_PRIVATI,IMP_OUT_CONTO_FAMIGLIE,
IMPORTO_TIPO_ENTRATA.IMP_IN_CONTO_BASE,IMP_IN_CONTO_BUSINESS,IMP_IN_CONTO_PRIVATI,IMP_IN_CONTO_FAMIGLIE
FROM ETA
JOIN N_TRANS_USCITA ON ETA.ID_CLIENTE = N_TRANS_USCITA.ID_CLIENTE
JOIN N_TRANS_ENTRATA ON ETA.ID_CLIENTE = N_TRANS_ENTRATA.ID_CLIENTE
JOIN IMP_TRANS_USCITA ON ETA.ID_CLIENTE = IMP_TRANS_USCITA.ID_CLIENTE
JOIN IMP_TRANS_ENTRATA ON ETA.ID_CLIENTE = IMP_TRANS_ENTRATA.ID_CLIENTE
JOIN COUNT_CONTO_ID ON ETA.ID_CLIENTE = COUNT_CONTO_ID.ID_CLIENTE
JOIN CONTO_TIPOLOGIA ON ETA.ID_CLIENTE = CONTO_TIPOLOGIA.ID_CLIENTE
JOIN TRANS_USCITA_TIPO ON ETA.ID_CLIENTE = TRANS_USCITA_TIPO.ID_CLIENTE
JOIN TRANS_ENTRATA_TIPO ON ETA.ID_CLIENTE = TRANS_ENTRATA_TIPO.ID_CLIENTE
JOIN IMPORTO_TIPO_USCITA ON ETA.ID_CLIENTE = IMPORTO_TIPO_USCITA.ID_CLIENTE
JOIN IMPORTO_TIPO_ENTRATA ON ETA.ID_CLIENTE = IMPORTO_TIPO_ENTRATA.ID_CLIENTE;

SELECT * FROM TABELLA_SINTESI;